export const trendingData = [
	{
		adult: false,
		backdrop_path: '/1syW9SNna38rSl9fnXwc9fP7POW.jpg',
		genre_ids: [28, 878, 12],
		id: 565770,
		original_language: 'en',
		original_title: 'Blue Beetle',
		overview:
			'Recent college grad Jaime Reyes returns home full of aspirations for his future, only to find that home is not quite as he left it. As he searches to find his purpose in the world, fate intervenes when Jaime unexpectedly finds himself in possession of an ancient relic of alien biotechnology: the Scarab.',
		popularity: 2972.534,
		poster_path: '/mXLOHHc1Zeuwsl4xYKjKh2280oL.jpg',
		release_date: '2023-08-16',
		title: 'Blue Beetle',
		video: false,
		vote_average: 7.2,
		vote_count: 956,
	},
	{
		adult: false,
		backdrop_path: '/iiXliCeykkzmJ0Eg9RYJ7F2CWSz.jpg',
		genre_ids: [28, 9648, 53, 80],
		id: 762430,
		original_language: 'en',
		original_title: 'Retribution',
		overview:
			"When a mysterious caller puts a bomb under his car seat, Matt Turner begins a high-speed chase across the city to complete a specific series of tasks. With his kids trapped in the back seat and a bomb that will explode if they get out of the car, a normal commute becomes a twisted game of life or death as Matt follows the stranger's increasingly dangerous instructions in a race against time to save his family.",
		popularity: 1484.504,
		poster_path: '/oUmmY7QWWn7OhKlcPOnirHJpP1F.jpg',
		release_date: '2023-08-23',
		title: 'Retribution',
		video: false,
		vote_average: 6.9,
		vote_count: 236,
	},
	{
		adult: false,
		backdrop_path: '/8pjWz2lt29KyVGoq1mXYu6Br7dE.jpg',
		genre_ids: [28, 878, 27],
		id: 615656,
		original_language: 'en',
		original_title: 'Meg 2: The Trench',
		overview:
			'An exploratory dive into the deepest depths of the ocean of a daring research team spirals into chaos when a malevolent mining operation threatens their mission and forces them into a high-stakes battle for survival.',
		popularity: 1322.828,
		poster_path: '/4m1Au3YkjqsxF8iwQy0fPYSxE0h.jpg',
		release_date: '2023-08-02',
		title: 'Meg 2: The Trench',
		video: false,
		vote_average: 7,
		vote_count: 1973,
	},
	{
		adult: false,
		backdrop_path: '/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg',
		genre_ids: [28, 80, 53],
		id: 385687,
		original_language: 'en',
		original_title: 'Fast X',
		overview:
			"Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the shadows of the past who's fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.",
		popularity: 1183.157,
		poster_path: '/fiVW06jE7z9YnO4trhaMEdclSiC.jpg',
		release_date: '2023-05-17',
		title: 'Fast X',
		video: false,
		vote_average: 7.3,
		vote_count: 3867,
	},
	{
		adult: false,
		backdrop_path: '/iIvQnZyzgx9TkbrOgcXx0p7aLiq.jpg',
		genre_ids: [27, 53],
		id: 1008042,
		original_language: 'en',
		original_title: 'Talk to Me',
		overview:
			'When a group of friends discover how to conjure spirits using an embalmed hand, they become hooked on the new thrill, until one of them goes too far and unleashes terrifying supernatural forces.',
		popularity: 1107.778,
		poster_path: '/kdPMUMJzyYAc4roD52qavX0nLIC.jpg',
		release_date: '2023-07-26',
		title: 'Talk to Me',
		video: false,
		vote_average: 7.2,
		vote_count: 899,
	},
	{
		adult: false,
		backdrop_path: '/53z2fXEKfnNg2uSOPss2unPBGX1.jpg',
		genre_ids: [27, 9648, 53],
		id: 968051,
		original_language: 'en',
		original_title: 'The Nun II',
		overview:
			'In 1956 France, a priest is violently murdered, and Sister Irene begins to investigate. She once again comes face-to-face with a powerful evil.',
		popularity: 1092.159,
		poster_path: '/c9kVD7W8CT5xe4O3hQ7bFWwk68U.jpg',
		release_date: '2023-09-06',
		title: 'The Nun II',
		video: false,
		vote_average: 6.5,
		vote_count: 339,
	},
	{
		adult: false,
		backdrop_path: '/ctMserH8g2SeOAnCw5gFjdQF8mo.jpg',
		genre_ids: [35, 12, 14],
		id: 346698,
		original_language: 'en',
		original_title: 'Barbie',
		overview:
			'Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.',
		popularity: 1062.817,
		poster_path: '/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
		release_date: '2023-07-19',
		title: 'Barbie',
		video: false,
		vote_average: 7.3,
		vote_count: 5045,
	},
	{
		adult: false,
		backdrop_path: '/jv4tiXAgaArMQo57jFMjvBEjmoa.jpg',
		genre_ids: [28, 18, 12],
		id: 980489,
		original_language: 'en',
		original_title: 'Gran Turismo',
		overview:
			'The ultimate wish-fulfillment tale of a teenage Gran Turismo player whose gaming skills won him a series of Nissan competitions to become an actual professional racecar driver.',
		popularity: 976.892,
		poster_path: '/51tqzRtKMMZEYUpSYkrUE7v9ehm.jpg',
		release_date: '2023-08-09',
		title: 'Gran Turismo',
		video: false,
		vote_average: 7.8,
		vote_count: 473,
	},
	{
		adult: false,
		backdrop_path: '/zYlgqIpqJ1VAbvFhRhktAzIybVs.jpg',
		genre_ids: [27, 878, 53],
		id: 820609,
		original_language: 'en',
		original_title: 'No One Will Save You',
		overview:
			"An exiled anxiety-ridden homebody must battle an alien who's found its way into her home.",
		popularity: 930.332,
		poster_path: '/ehGIDAMaYy6Eg0o8ga0oqflDjqW.jpg',
		release_date: '2023-09-22',
		title: 'No One Will Save You',
		video: false,
		vote_average: 7,
		vote_count: 276,
	},
	{
		adult: false,
		backdrop_path: '/oghHR3X0hIcvs7xqyoFjA0GAZWn.jpg',
		genre_ids: [53],
		id: 1002338,
		original_language: 'is',
		original_title: 'Napóleonsskjölin',
		overview:
			"A modern-day lawyer is sucked into an international conspiracy after being accused of a murder she didn't commit. Her only chance of freedom lies in uncovering the secret of an old German WWII aeroplane, long buried deep beneath the ice, before the CIA.",
		popularity: 749.07,
		poster_path: '/j2Or0w69bpPXrmkE0hpTzw6hzsr.jpg',
		release_date: '2023-01-26',
		title: 'Operation Napoleon',
		video: false,
		vote_average: 7.2,
		vote_count: 20,
	},
	{
		adult: false,
		backdrop_path: '/uAAAzo9efEZJJPtj4iNwFvrRaki.jpg',
		genre_ids: [28, 80, 878, 18],
		id: 744278,
		original_language: 'it',
		original_title: 'Mondocane',
		overview:
			'In the near future, the southern Italian city of Taranto is surrounded by barbed wire that no one, not even the police, dares to cross. The poorest are left fighting for survival, while gangs compete for the territory. Two thirteen-year-old orphans who grew up together, dream of joining one of the gangs.',
		popularity: 732.407,
		poster_path: '/gOuJBz9u1YVWwvx12lJX56yUT6I.jpg',
		release_date: '2021-09-03',
		title: 'Mondocane',
		video: false,
		vote_average: 6.4,
		vote_count: 113,
	},
	{
		adult: false,
		backdrop_path: '/c6Splshb8lb2Q9OvUfhpqXl7uP0.jpg',
		genre_ids: [28, 53],
		id: 717930,
		original_language: 'en',
		original_title: 'Kandahar',
		overview:
			'After his mission is exposed, an undercover CIA operative stuck deep in hostile territory in Afghanistan must fight his way out, alongside his Afghan translator, to an extraction point in Kandahar, all whilst avoiding elite enemy forces and foreign spies tasked with hunting them down.',
		popularity: 722.895,
		poster_path: '/lCanGgsqF4xD2WA5NF8PWeT3IXd.jpg',
		release_date: '2023-05-25',
		title: 'Kandahar',
		video: false,
		vote_average: 6.9,
		vote_count: 565,
	},
	{
		adult: false,
		backdrop_path: '/5xUJBgds96m6Xi2EtUpSzbw24D7.jpg',
		genre_ids: [53, 9648],
		id: 852436,
		original_language: 'fr',
		original_title: 'Seule : Les dossiers Silvercloud',
		overview:
			'Alone in the mountains of Switzerland, Anne discovers that her isolated chalet is on surveillance and has been bugged. Caught up by her former life as an intelligence secret agent and an affair with her handler, Anne can only count on herself to get out alive.',
		popularity: 699.61,
		poster_path: '/qx81rP4b4UFcxjabCqfe79F24Z0.jpg',
		release_date: '2023-03-08',
		title: 'Let Her Kill You',
		video: false,
		vote_average: 6.6,
		vote_count: 47,
	},
	{
		adult: false,
		backdrop_path: '/4fLZUr1e65hKPPVw0R3PmKFKxj1.jpg',
		genre_ids: [16, 35, 10751, 14, 10749],
		id: 976573,
		original_language: 'en',
		original_title: 'Elemental',
		overview:
			'In a city where fire, water, land and air residents live together, a fiery young woman and a go-with-the-flow guy will discover something elemental: how much they have in common.',
		popularity: 677.12,
		poster_path: '/4Y1WNkd88JXmGfhtWR7dmDAo1T2.jpg',
		release_date: '2023-06-14',
		title: 'Elemental',
		video: false,
		vote_average: 7.8,
		vote_count: 2403,
	},
	{
		adult: false,
		backdrop_path: '/iOJX54nVAsnPawagFiWXKv1Y6sB.jpg',
		genre_ids: [16, 12, 10751],
		id: 1076364,
		original_language: 'en',
		original_title: "Carl's Date",
		overview:
			"Carl Fredricksen reluctantly agrees to go on a date with a lady friend—but admittedly has no idea how dating works these days. Ever the helpful friend, Dug steps in to calm Carl's pre-date jitters and offer some tried-and-true tips for making friends—if you're a dog.",
		popularity: 648.421,
		poster_path: '/y8NtM6q3PzntqyNRNw6wgicwRYl.jpg',
		release_date: '2023-06-15',
		title: "Carl's Date",
		video: false,
		vote_average: 7.8,
		vote_count: 184,
	},
	{
		adult: false,
		backdrop_path: '/35z8hWuzfFUZQaYog8E9LsXW3iI.jpg',
		genre_ids: [12, 28],
		id: 335977,
		original_language: 'en',
		original_title: 'Indiana Jones and the Dial of Destiny',
		overview:
			"Finding himself in a new era, and approaching retirement, Indy wrestles with fitting into a world that seems to have outgrown him. But as the tentacles of an all-too-familiar evil return in the form of an old rival, Indy must don his hat and pick up his whip once more to make sure an ancient and powerful artifact doesn't fall into the wrong hands.",
		popularity: 607.636,
		poster_path: '/Af4bXE63pVsb2FtbW8uYIyPBadD.jpg',
		release_date: '2023-06-28',
		title: 'Indiana Jones and the Dial of Destiny',
		video: false,
		vote_average: 6.7,
		vote_count: 1742,
	},
	{
		adult: false,
		backdrop_path: '/waBWlJlMpyFb7STkFHfFvJKgwww.jpg',
		genre_ids: [28, 18],
		id: 678512,
		original_language: 'en',
		original_title: 'Sound of Freedom',
		overview:
			'The story of Tim Ballard, a former US government agent, who quits his job in order to devote his life to rescuing children from global sex traffickers.',
		popularity: 566.855,
		poster_path: '/kSf9svfL2WrKeuK8W08xeR5lTn8.jpg',
		release_date: '2023-07-03',
		title: 'Sound of Freedom',
		video: false,
		vote_average: 8,
		vote_count: 494,
	},
	{
		adult: false,
		backdrop_path: '/2vFuG6bWGyQUzYS9d69E5l85nIz.jpg',
		genre_ids: [28, 12, 878],
		id: 667538,
		original_language: 'en',
		original_title: 'Transformers: Rise of the Beasts',
		overview:
			'When a new threat capable of destroying the entire planet emerges, Optimus Prime and the Autobots must team up with a powerful faction known as the Maximals. With the fate of humanity hanging in the balance, humans Noah and Elena will do whatever it takes to help the Transformers as they engage in the ultimate battle to save Earth.',
		popularity: 547.076,
		poster_path: '/gPbM0MK8CP8A174rmUwGsADNYKD.jpg',
		release_date: '2023-06-06',
		title: 'Transformers: Rise of the Beasts',
		video: false,
		vote_average: 7.5,
		vote_count: 3262,
	},
	{
		adult: false,
		backdrop_path: '/6fKEw0I2FTD5FLOQ5q7L1tqf876.jpg',
		genre_ids: [10751, 35, 28, 12],
		id: 790493,
		original_language: 'en',
		original_title: 'Spy Kids: Armageddon',
		overview:
			'When the children of the world’s greatest secret agents unwittingly help a powerful game developer unleash a computer virus that gives him control of all technology, they must become spies themselves to save their parents and the world.',
		popularity: 525.935,
		poster_path: '/vd8YdaH7dzeIMGTNwQinlSiA1gV.jpg',
		release_date: '2023-09-22',
		title: 'Spy Kids: Armageddon',
		video: false,
		vote_average: 6.6,
		vote_count: 39,
	},
	{
		adult: false,
		backdrop_path: '/yF1eOkaYvwiORauRCPWznV9xVvi.jpg',
		genre_ids: [28, 12, 878],
		id: 298618,
		original_language: 'en',
		original_title: 'The Flash',
		overview:
			"When his attempt to save his family inadvertently alters the future, Barry Allen becomes trapped in a reality in which General Zod has returned and there are no Super Heroes to turn to. In order to save the world that he is in and return to the future that he knows, Barry's only hope is to race for his life. But will making the ultimate sacrifice be enough to reset the universe?",
		popularity: 486.095,
		poster_path: '/rktDFPbfHfUbArZ6OOOKsXcv0Bm.jpg',
		release_date: '2023-06-13',
		title: 'The Flash',
		video: false,
		vote_average: 6.9,
		vote_count: 2950,
	},
]

export const upcomingData = [
	{
		adult: false,
		backdrop_path: '/iiXliCeykkzmJ0Eg9RYJ7F2CWSz.jpg',
		genre_ids: [28, 9648, 53, 80],
		id: 762430,
		original_language: 'en',
		original_title: 'Retribution',
		overview:
			"When a mysterious caller puts a bomb under his car seat, Matt Turner begins a high-speed chase across the city to complete a specific series of tasks. With his kids trapped in the back seat and a bomb that will explode if they get out of the car, a normal commute becomes a twisted game of life or death as Matt follows the stranger's increasingly dangerous instructions in a race against time to save his family.",
		popularity: 1484.504,
		poster_path: '/oUmmY7QWWn7OhKlcPOnirHJpP1F.jpg',
		release_date: '2023-08-23',
		title: 'Retribution',
		video: false,
		vote_average: 6.9,
		vote_count: 236,
	},
	{
		adult: false,
		backdrop_path: '/53z2fXEKfnNg2uSOPss2unPBGX1.jpg',
		genre_ids: [27, 9648, 53],
		id: 968051,
		original_language: 'en',
		original_title: 'The Nun II',
		overview:
			'In 1956 France, a priest is violently murdered, and Sister Irene begins to investigate. She once again comes face-to-face with a powerful evil.',
		popularity: 1092.159,
		poster_path: '/c9kVD7W8CT5xe4O3hQ7bFWwk68U.jpg',
		release_date: '2023-09-06',
		title: 'The Nun II',
		video: false,
		vote_average: 6.5,
		vote_count: 339,
	},
	{
		adult: false,
		backdrop_path: '/waBWlJlMpyFb7STkFHfFvJKgwww.jpg',
		genre_ids: [28, 18],
		id: 678512,
		original_language: 'en',
		original_title: 'Sound of Freedom',
		overview:
			'The story of Tim Ballard, a former US government agent, who quits his job in order to devote his life to rescuing children from global sex traffickers.',
		popularity: 566.855,
		poster_path: '/kSf9svfL2WrKeuK8W08xeR5lTn8.jpg',
		release_date: '2023-07-03',
		title: 'Sound of Freedom',
		video: false,
		vote_average: 8,
		vote_count: 494,
	},
	{
		adult: false,
		backdrop_path: '/rMvPXy8PUjj1o8o1pzgQbdNCsvj.jpg',
		genre_ids: [28, 12, 53],
		id: 299054,
		original_language: 'en',
		original_title: 'Expend4bles',
		overview:
			'Armed with every weapon they can get their hands on and the skills to use them, The Expendables are the world’s last line of defense and the team that gets called when all other options are off the table. But new team members with new styles and tactics are going to give “new blood” a whole new meaning.',
		popularity: 460.286,
		poster_path: '/nbrqj9q8WubD3QkYm7n3GhjN7kE.jpg',
		release_date: '2023-09-15',
		title: 'Expend4bles',
		video: false,
		vote_average: 6.6,
		vote_count: 79,
	},
	{
		adult: false,
		backdrop_path: '/iQcCAm8hKWZyUntqrvzyEGtXyJl.jpg',
		genre_ids: [878, 28, 53],
		id: 670292,
		original_language: 'en',
		original_title: 'The Creator',
		overview:
			'Amid a future war between the human race and the forces of artificial intelligence, a hardened ex-special forces agent grieving the disappearance of his wife, is recruited to hunt down and kill the Creator, the elusive architect of advanced AI who has developed a mysterious weapon with the power to end the war—and mankind itself.',
		popularity: 371.899,
		poster_path: '/vBZ0qvaRxqEhZwl6LWmruJqWE8Z.jpg',
		release_date: '2023-09-27',
		title: 'The Creator',
		video: false,
		vote_average: 7.7,
		vote_count: 34,
	},
	{
		adult: false,
		backdrop_path: '/9b3uxqcjkmay20EBZZj1KVow0r5.jpg',
		genre_ids: [80, 27, 53],
		id: 951491,
		original_language: 'en',
		original_title: 'Saw X',
		overview:
			"Between the events of 'Saw' and 'Saw II', a sick and desperate John Kramer travels to Mexico for a risky and experimental medical procedure in hopes of a miracle cure for his cancer, only to discover the entire operation is a scam to defraud the most vulnerable. Armed with a newfound purpose, the infamous serial killer returns to his work, turning the tables on the con artists in his signature visceral way through devious, deranged, and ingenious traps.",
		popularity: 346.198,
		poster_path: '/aQPeznSu7XDTrrdCtT5eLiu52Yu.jpg',
		release_date: '2023-09-26',
		title: 'Saw X',
		video: false,
		vote_average: 7.5,
		vote_count: 16,
	},
	{
		adult: false,
		backdrop_path: '/h0nmmdFAdBjQttN8Y0q825MWzZp.jpg',
		genre_ids: [28, 53, 80],
		id: 926393,
		original_language: 'en',
		original_title: 'The Equalizer 3',
		overview:
			"Robert McCall finds himself at home in Southern Italy but he discovers his friends are under the control of local crime bosses. As events turn deadly, McCall knows what he has to do: become his friends' protector by taking on the mafia.",
		popularity: 311.412,
		poster_path: '/b0Ej6fnXAP8fK75hlyi2jKqdhHz.jpg',
		release_date: '2023-08-30',
		title: 'The Equalizer 3',
		video: false,
		vote_average: 6.9,
		vote_count: 240,
	},
	{
		adult: false,
		backdrop_path: '/qEm4FrkGh7kGoEiBOyGYNielYVc.jpg',
		genre_ids: [53, 27],
		id: 635910,
		original_language: 'en',
		original_title: 'The Last Voyage of the Demeter',
		overview:
			'The crew of the merchant ship Demeter attempts to survive the ocean voyage from Carpathia to London as they are stalked each night by a merciless presence onboard the ship.',
		popularity: 294.537,
		poster_path: '/nrtbv6Cew7qC7k9GsYSf5uSmuKh.jpg',
		release_date: '2023-08-09',
		title: 'The Last Voyage of the Demeter',
		video: false,
		vote_average: 7.3,
		vote_count: 700,
	},
	{
		adult: false,
		backdrop_path: '/yvotjJ9nKlPKiwc8PtktIjRCkof.jpg',
		genre_ids: [18, 36, 10749],
		id: 921452,
		original_language: 'fr',
		original_title: 'Jeanne du Barry',
		overview:
			'The life of Jeanne Bécu, who was born as the illegitimate daughter of an impoverished seamstress in 1743 and went on to rise through the Court of Louis XV to become his last official mistress.',
		popularity: 247.284,
		poster_path: '/6AXHh9H7XeUqxl8Ijp9ADkpxfM0.jpg',
		release_date: '2023-05-16',
		title: 'Jeanne du Barry',
		video: false,
		vote_average: 7,
		vote_count: 174,
	},
	{
		adult: false,
		backdrop_path: '/qZOuoBoKCDLSm1EvYz2eBub8Cto.jpg',
		genre_ids: [16, 12, 14, 10751],
		id: 939338,
		original_language: 'fr',
		original_title: 'Pattie et la colère de Poséidon',
		overview:
			'An adventurous mouse sets off to battle dangerous creatures in Ancient Greece, including Poseidon.',
		popularity: 246.134,
		poster_path: '/gVPw9gRPsZZhzY6cIXp6h6nep5M.jpg',
		release_date: '2023-01-25',
		title: 'Epic Tails',
		video: false,
		vote_average: 6.8,
		vote_count: 34,
	},
	{
		adult: false,
		backdrop_path: '/iEFuHjqrE059SmflBva1JzDJutE.jpg',
		genre_ids: [16, 10402, 10751, 28, 10749, 14, 35],
		id: 496450,
		original_language: 'fr',
		original_title: 'Miraculous - le film',
		overview:
			'A life of an ordinary Parisian teenager Marinette goes superhuman when she becomes Ladybug. Bestowed with magical powers of creation, Ladybug must unite with her opposite, Cat Noir, to save Paris as a new villain unleashes chaos unto the city.',
		popularity: 204.347,
		poster_path: '/dQNJ8SdCMn3zWwHzzQD2xrphR1X.jpg',
		release_date: '2023-07-05',
		title: 'Miraculous: Ladybug & Cat Noir, The Movie',
		video: false,
		vote_average: 7.8,
		vote_count: 593,
	},
	{
		adult: false,
		backdrop_path: '/vT17lPUglrAzjEqMwjPpIDe49ty.jpg',
		genre_ids: [16, 12, 10751, 14],
		id: 459003,
		original_language: 'uk',
		original_title: 'Мавка: Лісова пісня',
		overview:
			'Mavka — a Soul of the Forest and its Warden — faces an impossible choice between love and her duty as guardian to the Heart of the Forest, when she falls in love with a human — the talented young musician Lukas.',
		popularity: 190.337,
		poster_path: '/eeJjd9JU2Mdj9d7nWRFLWlrcExi.jpg',
		release_date: '2023-03-02',
		title: 'Mavka: The Forest Song',
		video: false,
		vote_average: 7.4,
		vote_count: 393,
	},
	{
		adult: false,
		backdrop_path: '/fwXeTKmJvlv7kbH8QDmbykGfMeK.jpg',
		genre_ids: [16, 10751, 35, 28, 878],
		id: 893723,
		original_language: 'en',
		original_title: 'PAW Patrol: The Mighty Movie',
		overview:
			"A magical meteor crash-lands in Adventure City, gives the PAW Patrol pups superpowers, and transforms them into The Mighty Pups. When the PAW Patrol's archrival Humdinger breaks out of jail and teams up with a mad scientist to steal the powers for themselves, the Mighty Pups must save Adventure City and stop the supervillains before it's too late.",
		popularity: 159.484,
		poster_path: '/oXnSu4raRAd65QVBQXvdHMC6AuW.jpg',
		release_date: '2023-09-21',
		title: 'PAW Patrol: The Mighty Movie',
		video: false,
		vote_average: 8.3,
		vote_count: 7,
	},
	{
		adult: false,
		backdrop_path: '/f33XdT6dwNXmXQNvQ4FuyhQrUob.jpg',
		genre_ids: [27],
		id: 807172,
		original_language: 'en',
		original_title: 'The Exorcist: Believer',
		overview:
			'Since the death of his wife 12 years ago, Victor Fielding has raised their daughter, Angela on his own. But when Angela and her friend Katherine disappear in the woods, only to return three days later with no memory of what happened to them, it unleashes a chain of events that will force Victor to confront the nadir of evil and, in his terror and desperation, seek out the only person alive who has witnessed anything like it before: Chris MacNeil.',
		popularity: 129.046,
		poster_path: '/thTULd2MorLIBbK90XF5mdxj4Ds.jpg',
		release_date: '2023-10-04',
		title: 'The Exorcist: Believer',
		video: false,
		vote_average: 0,
		vote_count: 0,
	},
	{
		adult: false,
		backdrop_path: '/8TGfsSTWypvkcOX5sqQ7EuMmQkA.jpg',
		genre_ids: [35],
		id: 986054,
		original_language: 'en',
		original_title: 'Theater Camp',
		overview:
			'After the indomitable and beloved founder of a scrappy theater camp in upstate New York falls into a coma, the eccentric staff must band together with her clueless "crypto-bro" son to keep the thespian paradise afloat.',
		popularity: 108.663,
		poster_path: '/2osbLk1MMt9qjXPKSB2hMcBUyrw.jpg',
		release_date: '2023-07-13',
		title: 'Theater Camp',
		video: false,
		vote_average: 6.6,
		vote_count: 53,
	},
	{
		adult: false,
		backdrop_path: '/uvsL5Q5Juf8ivqBnlr4nFVUwVoa.jpg',
		genre_ids: [80, 18, 53],
		id: 466420,
		original_language: 'en',
		original_title: 'Killers of the Flower Moon',
		overview:
			'When oil is discovered in 1920s Oklahoma under Osage Nation land, the Osage people are murdered one by one—until the FBI steps in to unravel the mystery.',
		popularity: 99.494,
		poster_path: '/dB6Krk806zeqd0YNp2ngQ9zXteH.jpg',
		release_date: '2023-10-18',
		title: 'Killers of the Flower Moon',
		video: false,
		vote_average: 0,
		vote_count: 0,
	},
	{
		adult: false,
		backdrop_path: '/9t0tJXcOdWwwxmGTk112HGDaT0Q.jpg',
		genre_ids: [27, 53],
		id: 890771,
		original_language: 'en',
		original_title: 'The Black Demon',
		overview:
			"Oilman Paul Sturges' idyllic family vacation turns into a nightmare when they encounter a ferocious megalodon shark that will stop at nothing to protect its territory. Stranded and under constant attack, Paul and his family must somehow find a way to get his family back to shore alive before it strikes again in this epic battle between humans and nature.",
		popularity: 98.42,
		poster_path: '/6ecSjKSjgIULyHfrfyyg9vgAI33.jpg',
		release_date: '2023-04-26',
		title: 'The Black Demon',
		video: false,
		vote_average: 6.2,
		vote_count: 512,
	},
	{
		adult: false,
		backdrop_path: '/7vxuOzbsDgGRKNiB9yzvSHaNlNi.jpg',
		genre_ids: [16, 12, 878],
		id: 1030587,
		original_language: 'ja',
		original_title: '映画ドラえもん のび太と空の理想郷',
		overview:
			'Doraemon, Nobita and his friends go to find Utopia, a perfect land in the sky where everyone lives with happiness, using an airship having a time warp function.',
		popularity: 97.882,
		poster_path: '/g9ksiIwYUUTWMR1PH22p8YAfUR1.jpg',
		release_date: '2023-03-03',
		title: "Doraemon: Nobita's Sky Utopia",
		video: false,
		vote_average: 7,
		vote_count: 19,
	},
	{
		adult: false,
		backdrop_path: '/bYpmDDNatiGvqa4iShuw5xTpMYt.jpg',
		genre_ids: [878, 35, 18],
		id: 1072371,
		original_language: 'en',
		original_title: 'Jules',
		overview:
			'A flying saucer lands in the backyard of an elderly suburbanite with memory problems, who forms a bond with the scared alien inside.',
		popularity: 75.141,
		poster_path: '/yMOWu8rpZPiBI0j8MInBTtNO0vU.jpg',
		release_date: '2023-08-10',
		title: 'Jules',
		video: false,
		vote_average: 7.8,
		vote_count: 61,
	},
	{
		adult: false,
		backdrop_path: '/T5xXoFqyc9jNXZIbH4Sw0jwWjw.jpg',
		genre_ids: [80, 53, 9648],
		id: 605886,
		original_language: 'en',
		original_title: 'Misanthrope',
		overview:
			"Baltimore. New Year's Eve. A talented but troubled police officer is recruited by the FBI's chief investigator to help profile and track down a mass murderer.",
		popularity: 68.166,
		poster_path: '/mFp3l4lZg1NSEsyxKrdi0rNK8r1.jpg',
		release_date: '2023-04-06',
		title: 'To Catch a Killer',
		video: false,
		vote_average: 7,
		vote_count: 526,
	},
]
